name: daily-cron-clear-trash
on:
  schedule:
    - cron: '*/6 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://bookmark-tags-git-dev-timelessco.vercel.app/api/bookmark/clear-bookmark-trash' \
